// <auto-generated />
using System;
using Consoltech.AdminApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consoltech.AdminApi.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20260122135212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consoltech.AdminApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Flags")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Flags = "featured,new",
                            ImageUrl = "/images/nintendo-switch-2-product.jpg",
                            Price = 449.99m,
                            Sku = "NS2-2024"
                        },
                        new
                        {
                            Id = 2,
                            Flags = "featured,new",
                            ImageUrl = "/images/bd80e124-a5e2-4d34-9c82-ebc0dbd6a697.png",
                            Price = 499.99m,
                            Sku = "PS5-STD"
                        },
                        new
                        {
                            Id = 3,
                            Flags = "new",
                            ImageUrl = "/images/78a95f48-606e-44b6-950e-af0555a3f04f.png",
                            Price = 449.99m,
                            Sku = "XSX-2024"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/07ba8bc0-8d14-4d62-a534-659913ac5f99.png",
                            Price = 1299.99m,
                            Sku = "DRN-PRO"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/a0bd3ab6-05d5-4312-b6ec-f0e256d7a63a.png",
                            Price = 1899.99m,
                            Sku = "EBIKE-SMART"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/images/6df37998-af04-426e-b749-365ffeb66787.png",
                            Price = 799.99m,
                            Sku = "TV-4K-55"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/images/bd80e124-a5e2-4d34-9c82-ebc0dbd6a697.png",
                            Price = 149.99m,
                            Sku = "GAME-ACC"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/images/6df37998-af04-426e-b749-365ffeb66787.png",
                            Price = 299.99m,
                            Sku = "SMART-HOME"
                        });
                });

            modelBuilder.Entity("Consoltech.AdminApi.Models.ProductTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Badges")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Locale");

                    b.ToTable("ProductTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badges = "Featured,Hot",
                            Category = "New Arrivals",
                            Description = "The next generation of Nintendo gaming. Experience enhanced graphics, faster performance, and an expanded game library. Features a larger display, improved Joy-Con controllers, and backward compatibility.",
                            Locale = "en",
                            ProductId = 1,
                            Title = "Nintendo Switch 2"
                        },
                        new
                        {
                            Id = 2,
                            Badges = "Featured",
                            Category = "New Arrivals",
                            Description = "Next-generation gaming console with ultra-fast SSD and ray tracing technology. Experience lightning-fast loading and stunning graphics.",
                            Locale = "en",
                            ProductId = 2,
                            Title = "PlayStation 5"
                        },
                        new
                        {
                            Id = 3,
                            Category = "New Arrivals",
                            Description = "The most powerful Xbox ever with 12 teraflops of GPU performance and Smart Delivery technology.",
                            Locale = "en",
                            ProductId = 3,
                            Title = "Xbox Series X"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Drones",
                            Description = "High-performance drones for commercial photography, surveying, and recreational flying with advanced stabilization.",
                            Locale = "en",
                            ProductId = 4,
                            Title = "Professional Drones"
                        },
                        new
                        {
                            Id = 5,
                            Category = "E-Bikes",
                            Description = "Electric bikes with smart connectivity, long-range batteries, and advanced motor systems for urban mobility.",
                            Locale = "en",
                            ProductId = 5,
                            Title = "Smart E-Bikes"
                        },
                        new
                        {
                            Id = 6,
                            Category = "TVs",
                            Description = "Ultra-high definition smart TVs with AI upscaling, HDR support, and built-in streaming platforms.",
                            Locale = "en",
                            ProductId = 6,
                            Title = "4K Smart TVs"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Gaming",
                            Description = "Premium gaming peripherals including controllers, headsets, and racing wheels from top brands.",
                            Locale = "en",
                            ProductId = 7,
                            Title = "Gaming Accessories"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            Description = "Connected home devices including smart speakers, security cameras, and automation systems.",
                            Locale = "en",
                            ProductId = 8,
                            Title = "Smart Home Electronics"
                        },
                        new
                        {
                            Id = 9,
                            Badges = "מומלץ,לוהט",
                            Category = "מוצרים חדשים",
                            Description = "הדור הבא של משחקי נינטנדו. חוו גרפיקה משופרת, ביצועים מהירים יותר וספריית משחקים מורחבת. כולל מסך גדול יותר, בקרי Joy-Con משופרים ותאימות לאחור.",
                            Locale = "he",
                            ProductId = 1,
                            Title = "נינטנדו סוויץ' 2"
                        },
                        new
                        {
                            Id = 10,
                            Badges = "מומלץ",
                            Category = "מוצרים חדשים",
                            Description = "קונסולת משחקים מהדור הבא עם SSD במהירות אולטרה וטכנולוגיית Ray Tracing. חוו טעינה במהירות הבזק וגרפיקה מדהימה.",
                            Locale = "he",
                            ProductId = 2,
                            Title = "פלייסטיישן 5"
                        },
                        new
                        {
                            Id = 11,
                            Category = "מוצרים חדשים",
                            Description = "ה-Xbox החזק ביותר אי פעם עם 12 teraflops של ביצועי GPU וטכנולוגיית Smart Delivery.",
                            Locale = "he",
                            ProductId = 3,
                            Title = "אקסבוקס סדרה X"
                        },
                        new
                        {
                            Id = 12,
                            Category = "רחפנים",
                            Description = "רחפנים בעלי ביצועים גבוהים לצילום מסחרי, סקרים וטיסות פנאי עם ייצוב מתקדם.",
                            Locale = "he",
                            ProductId = 4,
                            Title = "רחפנים מקצועיים"
                        },
                        new
                        {
                            Id = 13,
                            Category = "אופניים חשמליים",
                            Description = "אופניים חשמליים עם קישוריות חכמה, סוללות לטווח ארוך ומערכות מנוע מתקדמות לניידות עירונית.",
                            Locale = "he",
                            ProductId = 5,
                            Title = "אופניים חשמליים חכמים"
                        },
                        new
                        {
                            Id = 14,
                            Category = "טלוויזיות",
                            Description = "טלוויזיות חכמות ברזולוציה גבוהה במיוחד עם שדרוג AI, תמיכת HDR ופלטפורמות סטרימינג מובנות.",
                            Locale = "he",
                            ProductId = 6,
                            Title = "טלוויזיות חכמות 4K"
                        },
                        new
                        {
                            Id = 15,
                            Category = "משחקים",
                            Description = "ציוד היקפי משחקים פרימיום כולל בקרים, אוזניות והגאי מרוץ מהמותגים המובילים.",
                            Locale = "he",
                            ProductId = 7,
                            Title = "אביזרי גיימינג"
                        },
                        new
                        {
                            Id = 16,
                            Category = "אלקטרוניקה",
                            Description = "מכשירים מחוברים לבית כולל רמקולים חכמים, מצלמות אבטחה ומערכות אוטומציה.",
                            Locale = "he",
                            ProductId = 8,
                            Title = "אלקטרוניקה לבית חכם"
                        });
                });

            modelBuilder.Entity("Consoltech.AdminApi.Models.WarrantySubmissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InvoiceFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("InvoiceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RowKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("RowKey")
                        .IsUnique();

                    b.HasIndex("SerialNumber");

                    b.ToTable("WarrantySubmissions");
                });

            modelBuilder.Entity("Consoltech.AdminApi.Models.ProductTranslation", b =>
                {
                    b.HasOne("Consoltech.AdminApi.Models.Product", "Product")
                        .WithMany("Translations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Consoltech.AdminApi.Models.Product", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
